version: "3"

services:

  database:
    container_name: avaliacao-municipal
    image: postgres:9.6-alpine
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: avaliacao-municipal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
